Repository getsentry/sentry-python, pull requests merged in 2022-11, with the labels that each got.

#1590 feat(pymongo): add PyMongo integration
  .github/workflows/test-integration-pymongo.yml
  linter-requirements.txt
  sentry_sdk/integrations/pymongo.py
  setup.py
  tests/integrations/pymongo/__init__.py
  tests/integrations/pymongo/test_pymongo.py
  tox.ini
Labels: new-integration, Status: Backlog

#1702 feat(profiling): Extract more frame info
  sentry_sdk/client.py
  sentry_sdk/profiler.py
  tests/test_profiler.py
Labels: profiling

#1297 The Falcon integration for Falcon 3.0.1
  sentry_sdk/integrations/falcon.py
Labels: enhancement, help wanted, Integration: Falcon, Status: Backlog

#1756 fix(profiling): Resolve inherited method class names
  sentry_sdk/profiler.py
  tests/test_profiler.py
Labels: profiling

#1755 ref(profiling): Eagerly hash stack for profiles
  sentry_sdk/profiler.py
  tests/test_profiler.py
Labels: profiling
