Repository getsentry/sentry-python, pull requests merged in 2023-03, with the labels that each got.

#1830 feat(profiling): Set active thread id for quart
  sentry_sdk/integrations/quart.py
  tests/integrations/quart/test_quart.py
Labels: Status: Backlog, Status: Stale, Feature: Profiling

#1089 Add decorator for Sentry tracing
  .github/workflows/test-common.yml
  .github/workflows/test-integration-aiohttp.yml
  .github/workflows/test-integration-arq.yml
  .github/workflows/test-integration-asgi.yml
  .github/workflows/test-integration-aws_lambda.yml
  .github/workflows/test-integration-beam.yml
  .github/workflows/test-integration-boto3.yml
  .github/workflows/test-integration-bottle.yml
  .github/workflows/test-integration-celery.yml
  .github/workflows/test-integration-chalice.yml
  .github/workflows/test-integration-cloud_resource_context.yml
  .github/workflows/test-integration-django.yml
  .github/workflows/test-integration-falcon.yml
  .github/workflows/test-integration-fastapi.yml
  .github/workflows/test-integration-flask.yml
  .github/workflows/test-integration-gcp.yml
  .github/workflows/test-integration-gevent.yml
  .github/workflows/test-integration-httpx.yml
  .github/workflows/test-integration-huey.yml
  .github/workflows/test-integration-opentelemetry.yml
  .github/workflows/test-integration-pure_eval.yml
  .github/workflows/test-integration-pymongo.yml
  .github/workflows/test-integration-pyramid.yml
  .github/workflows/test-integration-quart.yml
  .github/workflows/test-integration-redis.yml
  .github/workflows/test-integration-rediscluster.yml
  .github/workflows/test-integration-requests.yml
  .github/workflows/test-integration-rq.yml
  .github/workflows/test-integration-sanic.yml
  .github/workflows/test-integration-sqlalchemy.yml
  .github/workflows/test-integration-starlette.yml
  .github/workflows/test-integration-starlite.yml
  .github/workflows/test-integration-tornado.yml
  .github/workflows/test-integration-trytond.yml
  scripts/split-tox-gh-actions/ci-yaml.txt
  scripts/split-tox-gh-actions/split-tox-gh-actions.py
  sentry_sdk/__init__.py
  sentry_sdk/tracing.py
  sentry_sdk/tracing_utils_py2.py
  sentry_sdk/tracing_utils_py3.py
  tests/integrations/asyncio/__init__.py
  tests/integrations/asyncio/test_asyncio_py3.py
  tests/integrations/stdlib/test_httplib.py
  tests/tracing/test_decorator_py2.py
  tests/tracing/test_decorator_py3.py
  tox.ini
Labels: enhancement, Feature: Performance, Status: Backlog

#1970 ref: Forward all `sentry-` baggage items
  sentry_sdk/tracing_utils.py
  tests/tracing/test_baggage.py
Labels: enhancement
