Repository getsentry/sentry-python, pull requests merged in 2023-01, with the labels that each got.

#1024 feat(rq): Add enqueued_at and started_at to rq job extra
  sentry_sdk/integrations/rq.py
  tests/integrations/rq/test_rq.py
Labels: Status: Backlog

#1789 perf(profiling): Performance tweaks to profile sampler
  sentry_sdk/profiler.py
  tests/test_profiler.py
Labels: profiling

#1791 ref(profiling): Remove sample buffer from profiler
  sentry_sdk/profiler.py
  tests/test_profiler.py
Labels: profiling

#1802 Sorted integrations alphabetically
  tox.ini
Labels: end-of-year-cleanup

#1795 Added Python 3.11 to test suite
  .github/workflows/test-integration-aiohttp.yml
  .github/workflows/test-integration-asgi.yml
  .github/workflows/test-integration-bottle.yml
  .github/workflows/test-integration-django.yml
  .github/workflows/test-integration-falcon.yml
  .github/workflows/test-integration-fastapi.yml
  .github/workflows/test-integration-flask.yml
  .github/workflows/test-integration-httpx.yml
  .github/workflows/test-integration-opentelemetry.yml
  .github/workflows/test-integration-pure_eval.yml
  .github/workflows/test-integration-pymongo.yml
  .github/workflows/test-integration-pyramid.yml
  .github/workflows/test-integration-quart.yml
  .github/workflows/test-integration-rq.yml
  .github/workflows/test-integration-sanic.yml
  .github/workflows/test-integration-sqlalchemy.yml
  .github/workflows/test-integration-starlette.yml
  .github/workflows/test-integration-tornado.yml
  .github/workflows/test-integration-trytond.yml
  scripts/split-tox-gh-actions/ci-yaml-services.txt
  tox.ini
Labels: end-of-year-cleanup

#1748 Feat: add Starlite integration
  .github/workflows/test-integration-starlite.yml
  .tool-versions
  sentry_sdk/consts.py
  sentry_sdk/integrations/starlite.py
  sentry_sdk/utils.py
  setup.py
  tests/integrations/starlite/__init__.py
  tests/integrations/starlite/test_starlite.py
  tests/utils/test_transaction.py
  tox.ini
Labels: new-integration, Status: Backlog

#1825 fix extra dependency
  setup.py
Labels: dependencies, Status: Backlog

#1841 Fix middleware being patched multiple times when using FastAPI
  sentry_sdk/integrations/starlette.py
Labels: bug, Status: Backlog

#1555 feat(huey): add Huey Integration
  .github/workflows/test-integration-huey.yml
  mypy.ini
  sentry_sdk/consts.py
  sentry_sdk/integrations/huey.py
  setup.py
  tests/integrations/huey/__init__.py
  tests/integrations/huey/test_huey.py
  tox.ini
Labels: enhancement, new-integration, Status: Backlog

#1797 feat(profiling): Enable profiling on all transactions
  sentry_sdk/hub.py
  sentry_sdk/integrations/asgi.py
  sentry_sdk/integrations/django/asgi.py
  sentry_sdk/integrations/django/views.py
  sentry_sdk/integrations/fastapi.py
  sentry_sdk/integrations/starlette.py
  sentry_sdk/integrations/wsgi.py
  sentry_sdk/profiler.py
  sentry_sdk/tracing.py
  tests/integrations/django/asgi/test_asgi.py
  tests/integrations/fastapi/test_fastapi.py
  tests/integrations/starlette/test_starlette.py
  tests/test_profiler.py
Labels: Feature: Profiling

#1873 Do not overwrite default for username with email address in Flask-Login integration
  sentry_sdk/integrations/flask.py
Labels: bug, Integration: Flask
