Repository getsentry/sentry-python, pull requests merged in 2024-11, with the labels that each got.

#3648 Add LaunchDarkly and OpenFeature integration
  .github/workflows/test-integrations-miscellaneous.yml
  mypy.ini
  requirements-linting.txt
  scripts/split-tox-gh-actions/split-tox-gh-actions.py
  sentry_sdk/_lru_cache.py
  sentry_sdk/consts.py
  sentry_sdk/flag_utils.py
  sentry_sdk/integrations/launchdarkly.py
  sentry_sdk/integrations/openfeature.py
  sentry_sdk/scope.py
  setup.py
  tests/integrations/launchdarkly/__init__.py
  tests/integrations/launchdarkly/test_launchdarkly.py
  tests/integrations/openfeature/__init__.py
  tests/integrations/openfeature/test_openfeature.py
  tests/test_flag_utils.py
  tests/test_lru_cache.py
  tox.ini
Labels: New Integration

#3686 Make Anthropic integration work with Potel
  sentry_sdk/integrations/anthropic.py
  tests/integrations/anthropic/test_anthropic.py
Labels: Project: POTel (Phase 1)

#3732 Moved `_serialize_span_attribute` into `set_attribute`
  sentry_sdk/integrations/anthropic.py
  sentry_sdk/tracing.py
  sentry_sdk/tracing_utils.py
Labels: Project: POTel (Phase 1)

#3731 Fix Cohere tests
  tests/integrations/cohere/test_cohere.py
Labels: Project: POTel (Phase 1)

#3742 Fix(Arq): fix integration with Worker settings as a dict
  sentry_sdk/integrations/arq.py
  tests/integrations/arq/test_arq.py
Labels: Trigger: tests using secrets

#3745 [issue-2804] Handle the parameter `stack_info` for the `LoggingIntegration`
  sentry_sdk/integrations/logging.py
  tests/integrations/logging/test_logging.py
Labels: Trigger: tests using secrets

#3717 feat: introduce rust_tracing integration
  sentry_sdk/integrations/rust_tracing.py
  tests/integrations/rust_tracing/__init__.py
  tests/integrations/rust_tracing/test_rust_tracing.py
Labels: Enhancement

#3807 Update openai.py
  sentry_sdk/integrations/openai.py
Labels: Trigger: tests using secrets

#3803 fix(integrations): Check retries_left before capturing exception
  sentry_sdk/integrations/rq.py
  tests/integrations/rq/test_rq.py
Labels: Trigger: tests using secrets

#3540 Auto enable Litestar integration
  sentry_sdk/integrations/__init__.py
Labels: Trigger: tests using secrets
