Repository getsentry/sentry-python, pull requests merged in 2024-10, with the labels that each got.

#3313 fix(tracing): Fix `add_query_source` with modules outside of project root
  sentry_sdk/tracing_utils.py
  tests/test_tracing_utils.py
Labels: Trigger: tests using secrets

#3586 Fix `make aws lambda layer`
  requirements-aws-lambda-layer.txt
Labels: Project: POTel (Phase 1)

#3588 feat: Add httpcore based HTTP2Transport
  requirements-testing.txt
  sentry_sdk/client.py
  sentry_sdk/consts.py
  sentry_sdk/transport.py
  setup.py
  tests/integrations/excepthook/test_excepthook.py
  tests/test.key
  tests/test.pem
  tests/test_client.py
  tests/test_transport.py
  tests/test_utils.py
Labels: Trigger: tests using secrets

#3600 feat(django): Add SpotlightMiddleware when Spotlight is enabled
  sentry_sdk/client.py
  sentry_sdk/spotlight.py
  tests/integrations/django/test_basic.py
Labels: Trigger: tests using secrets

#3614 fix: Open relevant error when SpotlightMiddleware is on
  sentry_sdk/client.py
  sentry_sdk/spotlight.py
Labels: Trigger: tests using secrets

#3580 fix(django): improve getting psycopg3 connection info
  sentry_sdk/integrations/django/__init__.py
Labels: Trigger: tests using secrets

#3612 feat: Add opportunistic Brotli compression
  requirements-testing.txt
  sentry_sdk/consts.py
  sentry_sdk/transport.py
  tests/integrations/aiohttp/test_aiohttp.py
  tests/test_transport.py
Labels: Trigger: tests using secrets

#3574 Declare 3.13 support
  setup.py
Labels: Python:3.13

#3628 Fix database span `op`.
  sentry_sdk/integrations/opentelemetry/utils.py
Labels: Project: POTel (Phase 1)

#3631 Fix redis pipeline commands
  MIGRATION_GUIDE.md
  sentry_sdk/integrations/redis/utils.py
  tests/integrations/redis/asyncio/test_redis_asyncio.py
  tests/integrations/redis/cluster/test_redis_cluster.py
  tests/integrations/redis/cluster_asyncio/test_redis_cluster_asyncio.py
  tests/integrations/redis/test_redis.py
  tests/integrations/redis_py_cluster_legacy/test_redis_py_cluster_legacy.py
Labels: Project: POTel (Phase 1)

#3638 Fix clickhouse-driver integration spans
  MIGRATION_GUIDE.md
  sentry_sdk/integrations/clickhouse_driver.py
  sentry_sdk/tracing.py
  tests/integrations/clickhouse_driver/test_clickhouse_driver.py
Labels: Project: POTel (Phase 1)

#3615 Fix Anthropic integration when using tool calls
  sentry_sdk/integrations/anthropic.py
  tests/integrations/anthropic/test_anthropic.py
Labels: Trigger: tests using secrets

#3633 Fix tests using `_span_recorder`
  tests/integrations/aiohttp/test_aiohttp.py
  tests/integrations/httpx/test_httpx.py
  tests/integrations/stdlib/test_httplib.py
Labels: Project: POTel (Phase 1)

#3656 fix(langchain): handle case when parent span wasn't traced
  sentry_sdk/integrations/langchain.py
Labels: Trigger: tests using secrets

#3665 fix(spotlight): More defensive Django spotlight middleware injection
  sentry_sdk/spotlight.py
  tests/integrations/django/test_basic.py
Labels: Trigger: tests using secrets

#3497 Add support for async calls in Anthropic and OpenAI integration
  sentry_sdk/integrations/anthropic.py
  sentry_sdk/integrations/openai.py
  tests/integrations/anthropic/test_anthropic.py
  tests/integrations/openai/test_openai.py
  tox.ini
Labels: Trigger: tests using secrets

#3667 docs(sdk): Enhance README with improved clarity and developer-friendly examples
  README.md
Labels: Trigger: tests using secrets

#3637 Move `subprocess` breadcrumbs from `maybe_create_breadcrumbs_from_span` to integration.
  sentry_sdk/integrations/stdlib.py
  sentry_sdk/tracing_utils.py
  tests/integrations/stdlib/test_subprocess.py
  tests/test_breadcrumbs.py
Labels: Project: POTel (Phase 1)

#3680 Fix breadcrumbs in redis
  sentry_sdk/integrations/redis/_async_common.py
  sentry_sdk/integrations/redis/_sync_common.py
  sentry_sdk/integrations/redis/modules/caches.py
  sentry_sdk/integrations/redis/modules/queries.py
  sentry_sdk/integrations/redis/rb.py
  sentry_sdk/integrations/redis/redis.py
  sentry_sdk/integrations/redis/redis_cluster.py
  sentry_sdk/integrations/redis/redis_py_cluster_legacy.py
  sentry_sdk/integrations/redis/utils.py
  sentry_sdk/tracing_utils.py
  tests/integrations/redis/test_redis.py
  tests/integrations/redis/test_redis_cache_module.py
  tests/integrations/redis/test_redis_cache_module_async.py
Labels: Project: POTel (Phase 1)

#3602 Enable back pressure monitor in Potel
  sentry_sdk/integrations/opentelemetry/potel_span_processor.py
  sentry_sdk/integrations/opentelemetry/sampler.py
  tests/test_monitor.py
Labels: Project: POTel (Phase 1)

#3669 fix(profiling): Update active thread for asgi
  sentry_sdk/integrations/django/asgi.py
  sentry_sdk/integrations/django/views.py
  sentry_sdk/integrations/fastapi.py
  sentry_sdk/integrations/quart.py
  sentry_sdk/integrations/starlette.py
  sentry_sdk/tracing.py
  tests/integrations/django/asgi/test_asgi.py
  tests/integrations/fastapi/test_fastapi.py
  tests/integrations/quart/test_quart.py
  tests/integrations/starlette/test_starlette.py
Labels: Feature: Profiling

#3683 Fix breadcrumbs in HTTP clients
  sentry_sdk/integrations/aiohttp.py
  sentry_sdk/integrations/boto3.py
  sentry_sdk/integrations/httpx.py
  sentry_sdk/integrations/redis/_async_common.py
  sentry_sdk/integrations/redis/_sync_common.py
  sentry_sdk/integrations/redis/modules/caches.py
  sentry_sdk/integrations/redis/modules/queries.py
  sentry_sdk/integrations/redis/redis_cluster.py
  sentry_sdk/integrations/stdlib.py
  sentry_sdk/tracing_utils.py
  tests/integrations/boto3/test_s3.py
  tests/integrations/redis/test_redis.py
Labels: Project: POTel (Phase 1)
