Repository getsentry/sentry-python, pull requests merged in 2024-04, with the labels that each got.

#2933 feat(metrics): Implement metric_bucket rate limits
  sentry_sdk/transport.py
  tests/test_transport.py
Labels: Feature: Metrics, Component: Transport

#2938 Run tests in new tooling
  .github/workflows/test-integrations-databases.yml
  .github/workflows/test-integrations-web-frameworks-1.yml
  scripts/runtox.sh
  scripts/split-tox-gh-actions/templates/test_group.jinja
  tests/integrations/asyncpg/test_asyncpg.py
  tests/integrations/django/asgi/test_asgi.py
  tests/integrations/django/myapp/settings.py
  tox.ini
Labels: do not merge

#2758 feat(integrations): add django signals_denylist to filter signals that are attached to by signals_span
  sentry_sdk/integrations/django/__init__.py
  sentry_sdk/integrations/django/signals_handlers.py
  tests/integrations/django/myapp/signals.py
  tests/integrations/django/myapp/urls.py
  tests/integrations/django/myapp/views.py
  tests/integrations/django/test_basic.py
Labels: Trigger: tests using secrets

#2690 Remove outdated pins
  .github/dependabot.yml
  .github/workflows/test-integrations-aws-lambda.yml
  .github/workflows/test-integrations-cloud-computing.yml
  .github/workflows/test-integrations-common.yml
  .github/workflows/test-integrations-data-processing.yml
  .github/workflows/test-integrations-databases.yml
  .github/workflows/test-integrations-graphql.yml
  .github/workflows/test-integrations-miscellaneous.yml
  .github/workflows/test-integrations-networking.yml
  .github/workflows/test-integrations-web-frameworks-1.yml
  .github/workflows/test-integrations-web-frameworks-2.yml
  linter-requirements.txt
  scripts/runtox.sh
  scripts/split-tox-gh-actions/templates/test_group.jinja
  test-requirements.txt
  tests/integrations/asyncpg/test_asyncpg.py
  tests/integrations/beam/test_beam.py
  tests/integrations/django/asgi/test_asgi.py
  tests/integrations/django/myapp/settings.py
  tests/integrations/django/test_basic.py
  tests/integrations/rq/test_rq.py
  tests/integrations/sqlalchemy/test_sqlalchemy.py
  tox.ini
Labels: do not merge, SDK 2.0

#2954 fix(metrics): Change `data_category` from `statsd` to `metric_bucket`
  sentry_sdk/_types.py
  sentry_sdk/envelope.py
  sentry_sdk/transport.py
Labels: Type: Bug

#2979 [2.0] Tweak migration guide
  MIGRATION_GUIDE.md
Labels: SDK 2.0

#3027 fix: fix Django ASGI integration on Python 3.12
  sentry_sdk/integrations/django/asgi.py
  tests/integrations/django/asgi/test_asgi.py
Labels: Trigger: tests using secrets
