Repository getsentry/sentry-python, pull requests merged in 2024-12, with the labels that each got.

#3838 Fix Redis tests for potel
  sentry_sdk/integrations/redis/_sync_common.py
  tests/integrations/redis/asyncio/test_redis_asyncio.py
  tests/integrations/redis/cluster/test_redis_cluster.py
  tests/integrations/redis/cluster_asyncio/test_redis_cluster_asyncio.py
  tests/integrations/redis/test_redis.py
  tests/integrations/redis/test_redis_cache_module.py
  tests/integrations/redis/test_redis_cache_module_async.py
  tox.ini
Labels: Project: POTel

#3848 Fix Cohere tests in potel
  tests/integrations/cohere/test_cohere.py
Labels: Project: POTel

#3844 Fix boto3 tests in potel
  sentry_sdk/integrations/boto3.py
  tests/integrations/boto3/test_s3.py
Labels: Project: POTel

#3843 Fix Huey tests to work with POTel
  sentry_sdk/integrations/huey.py
  sentry_sdk/tracing.py
  tests/integrations/huey/test_huey.py
Labels: Project: POTel

#3205 fix(grpc): Return proper metadata object instead of list in…
  sentry_sdk/integrations/grpc/aio/client.py
Labels: Trigger: tests using secrets

#3864 Fix common tests in Potel
  sentry_sdk/scope.py
  sentry_sdk/utils.py
  tests/test_basics.py
  tests/test_utils.py
Labels: Project: POTel

#3875 Fix arq tests in POTel
  sentry_sdk/integrations/arq.py
  sentry_sdk/tracing.py
  tests/integrations/opentelemetry/test_potel.py
Labels: Project: POTel

#3877 Fix ray tests in POTel
  sentry_sdk/integrations/ray.py
  tests/integrations/ray/test_ray.py
Labels: Project: POTel

#3869 ✨ Add Typer integration
  .github/workflows/test-integrations-misc.yml
  requirements-linting.txt
  scripts/split-tox-gh-actions/split-tox-gh-actions.py
  sentry_sdk/integrations/typer.py
  tests/integrations/typer/__init__.py
  tests/integrations/typer/test_typer.py
  tox.ini
Labels: Trigger: tests using secrets

#3411 Support SparkIntegration activation after SparkContext created
  sentry_sdk/integrations/spark/spark_driver.py
  tests/integrations/asgi/test_asgi.py
  tests/integrations/spark/test_spark.py
Labels: Waiting for: Community, Trigger: tests using secrets

#3883 Fix lru cache copying
  sentry_sdk/_lru_cache.py
  tests/test_lru_cache.py
  tests/test_scope.py
Labels: Trigger: tests using secrets

#3738 Fix OpenAI tests in POTel
  tests/integrations/openai/test_openai.py
Labels: Project: POTel
