Repository getsentry/sentry-python, pull requests merged in 2025-01, with the labels that each got.

#3903 fix: preserve ARQ enqueue_job __kwdefaults__ after patching
  sentry_sdk/integrations/arq.py
Labels: Trigger: tests using secrets

#3888 feat(flags): add Unleash feature flagging integration
  .github/workflows/test-integrations-misc.yml
  requirements-linting.txt
  scripts/split_tox_gh_actions/split_tox_gh_actions.py
  sentry_sdk/integrations/unleash.py
  setup.py
  tests/conftest.py
  tests/integrations/unleash/__init__.py
  tests/integrations/unleash/test_unleash.py
  tests/integrations/unleash/testutils.py
  tox.ini
Labels: New Integration

#3884 Cleanup start_transaction usages
  sentry_sdk/integrations/aws_lambda.py
  sentry_sdk/integrations/celery/__init__.py
  sentry_sdk/integrations/gcp.py
  sentry_sdk/integrations/grpc/aio/server.py
  sentry_sdk/integrations/grpc/server.py
  sentry_sdk/integrations/tornado.py
  sentry_sdk/utils.py
  tests/integrations/aiohttp/test_aiohttp.py
  tests/integrations/anthropic/test_anthropic.py
  tests/integrations/arq/test_arq.py
  tests/integrations/celery/test_celery.py
  tests/integrations/celery/test_update_celery_task_headers.py
  tests/integrations/clickhouse_driver/test_clickhouse_driver.py
  tests/integrations/cohere/test_cohere.py
  tests/integrations/django/test_cache_module.py
  tests/integrations/django/test_db_query_data.py
  tests/integrations/huggingface_hub/test_huggingface_hub.py
  tests/integrations/langchain/test_langchain.py
  tests/integrations/openai/test_openai.py
  tests/integrations/redis/test_redis_cache_module.py
  tests/integrations/redis_py_cluster_legacy/test_redis_py_cluster_legacy.py
  tests/integrations/socket/test_socket.py
  tests/integrations/tornado/test_tornado.py
  tests/profiler/test_continuous_profiler.py
  tests/profiler/test_transaction_profiler.py
  tests/test_ai_monitoring.py
  tests/test_basics.py
  tests/test_scope.py
  tests/test_scrubber.py
Labels: Project: POTel

#3879 Fix AWS tests in POTel
  sentry_sdk/integrations/aws_lambda.py
  tests/integrations/aws_lambda/test_aws.py
Labels: Project: POTel

#3899 ref(tracing): Deprecate `propagate_traces` option.
  sentry_sdk/integrations/celery/__init__.py
  sentry_sdk/scope.py
  tests/integrations/celery/test_celery.py
  tests/tracing/test_integration_tests.py
Labels: Trigger: tests using secrets

#3772 Fix Celery tests in POTel
  sentry_sdk/integrations/celery/__init__.py
  tests/integrations/celery/test_celery.py
Labels: Project: POTel

#4001 Handle MultiPartParserError to avoid internal sentry crash
  sentry_sdk/integrations/_wsgi_common.py
Labels: Trigger: tests using secrets
